### ISSUE TITLE
DependencyDetails: Handling of 'classifier' in addition to group, name and version?

### ISSUE THREAD

**Issue by hbitteur** [jwharm/sources-list-plugin#2]
Hello,

And thank you for this plugin!

For the [Audiveris project](https://github.com/Audiveris/audiveris/tree/development), the building of a Flatpak version requires to identify all dependencies so that the flatpak-builder tool can download them.

Martin Wilck (@mwilck) has crafted an ad-hoc solution which roughly runs Gradle with a temporary (empty) cache. Once  filled, the cache is then analyzed by a specific Python program to populate a dependency.yml file. Details are available [here](https://github.com/Audiveris/audiveris/tree/development/dev/flatpak).

But this process of getting a complete dependency list has nothing to do with the Audiveris project. Hence my growing interest in your program, which is a Gradle plugin dedicated to this task.

Running your plugin on the Audiveris project, I noticed 2 differences among the 50+ dependencies.
- Your plugin adds itself, plus the dependent gson utility, which is understandable.
- It misses however 2 dependencies, even though they are specified in the runtimeOnly section of Audiveris `build.gradle` file, as follows:
```
dependencies {
    implementation(
        ...
    )
     runtimeOnly(
        [group: 'org.bytedeco', name: 'leptonica', version: "${leptVersion}-${jcppVersion}", classifier: "${project.ext.hostOS}"],
        [group: 'org.bytedeco', name: 'tesseract', version: "${tessVersion}-${jcppVersion}", classifier: "${project.ext.hostOS}"]
    )
}
```   
Depending on `hostOS` value (in our case: `windows-x86_64`, `linux-x86_64` or `linux-arm64`), the jar file will be different.

I checked in your Java code, there is yet no such '`classifier`' attribute in the DependencyDetails class.
Is it something you could consider?

Thanks in advance for any information.
/Hervé

**Comment by jwharm** [comment]
This is interesting.

I cannot add the classifier to the `DependencyDetails`, because in Gradle the classifier is an attribute of the artifact (i.e. the jar file), and not really related to the dependency info like g/a/v.

**Comment by hbitteur** [comment]
Well, here is the content of the Gradle cache for the  `org.bytedeco` group:
```
$ pwd
/cygdrive/d/soft/audiveris-github/bugfix/temp/gradle-windows/caches/modules-2/files-2.1/org.bytedeco

$ tree
.
├── javacpp
│   └── 1.5.9
│       ├── 2b3589e991cadf80be45720d3504ebfe691872cd
│       │   └── javacpp-1.5.9.pom
│       └── bee92b783ea619381df7577527f8739f778cf2f6
│           └── javacpp-1.5.9.jar
├── javacpp-presets
│   └── 1.5.9
│       └── a0d0fa786335540f3d7b3a872dc703a3e94d1f9d
│           └── javacpp-presets-1.5.9.pom
├── leptonica
│   └── 1.83.0-1.5.9
│       ├── 36cb477cb44ea062f560acf20ff53aef9f2ee01d
│       │   └── leptonica-1.83.0-1.5.9.pom
│       ├── 4d51ebe4e83119dcc2502c8342f8154263ffbbb1
│       │   └── leptonica-1.83.0-1.5.9-windows-x86_64.jar
│       └── 60091a4a7700fa91e996e86fe589eebbadab96d8
│           └── leptonica-1.83.0-1.5.9.jar
└── tesseract
    └── 5.3.1-1.5.9
        ├── 26a2706085e740c73ee7ffc70064081ac78e0c90
        │   └── tesseract-5.3.1-1.5.9-windows-x86_64.jar
        ├── 45fb19b331ad0ae717d0857631ad0ce7d94b5dda
        │   └── tesseract-5.3.1-1.5.9.pom
        └── d51335e63cb91cda213bf70d0ec49f7bf3bb1197
            └── tesseract-5.3.1-1.5.9.jar

17 directories, 9 files
```
We can see that, for both `leptonica` and `tesseract`, we have two .jar files with different names and sizes.
Taking the `tesseract` example, we have:
```
$ ls -og tesseract/5.3.1-1.5.9/d51335e63cb91cda213bf70d0ec49f7bf3bb1197/
total 60
-rwxrwxr-x+ 1 58705 Apr 14 18:45 tesseract-5.3.1-1.5.9.jar

$ ls -og tesseract/5.3.1-1.5.9/26a2706085e740c73ee7ffc70064081ac78e0c90/
total 1744
-rwxrwxr-x+ 1 1785627 Apr 14 18:46 tesseract-5.3.1-1.5.9-windows-x86_64.jar
```

The sizes are significantly different.
Perhaps the smaller file is a kind of API and the larger one an OS-dependent implementation.
But this is just a guess, I need to further investigate the role of each file.

**Comment by hbitteur** [comment]
I just made a few tests with the `build.gradle` file:

1. Removing the API from the implementation sub-section , while keeping the OS-dependent in the runtimeOnly sub-section.
The Java compilation fails with:
error: package org.bytedeco.tesseract does not exist
2. Moving up the OS-dependent from runtimeOnly to implementation sub-section (API still removed)
The Java compilation still fails:
_error: package org.bytedeco.tesseract does not exist_
3. Keeping the API, but removing the OS-dependent
Compilation is now OK
But at run time, I get:
_Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnileptonica in java.library.path_

So, I'm afraid Audiveris needs both jar files: the API jar and the OS-dependent jar.

I suspect the plugin wrongly considers these two dependencies as "equal", because it does not take the 'classifier' attribute into account, but just the tuple (group, name, version).

**Comment by jwharm** [comment]
I published release 1.1.0 that fixes the problem with the 'classifier' attribute.

I also tried building the Audiveris flatpak to verify.

Gradle complained it cannot download the plugin (`could not resolve plugin artifact 'io.github.jwharm.flatpak-gradle-generator:io.github.jwharm.flatpak-gradle-generator.gradle.plugin:1.0.0'`). I added the offline repository to `settings.gradle` to resolve this:
 ```
pluginManagement {
  repositories {
    maven { url="dependencies" }
  }
}
```
Afterwards, the compile, jar and test tasks ran fine. However, the build failed when it started to build a subproject (`:schemas`). You will have to add the `flatpakGradleGenerator` task to all subprojects, and add the resulting json files to the flatpak sources. (I tried to automate this in the plugin, but [Gradle doesn't allow this](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors).)

Note: It takes several minutes to generate the dependencies file. You can speed this up by moving the `mavenCentral` repository above the other repositories in `gradle.build`, because the plugin tries to resolve all artifacts against the repositories in the order that they appear in the build script, and most dependenies are on Maven Central.

If you encounter any other issues, please let me know.

**Comment by hbitteur** [comment]
Thanks a lot for this new release.
I will jump on it immediately.

Audiveris flatpak is a work in progress. Today, it stands half way between the previous ad hoc implementation and the future Gradle + plugin implementation. There is also a flatpak.yml in github workflow actions, which will need modifications.

Getting easily all the dependencies by simply calling your plugin is already an important simplification.

I have a question about the modification you made in `settings.gradle` to download the plugin while building Audiveris flatpak:
- Phase 1: we need to identify all dependencies. Your plugin is used here to generate the `dependencies.json` file
- Phase 2: flatpak-builder uses the manifest (which points to `dependencies.json` among other things) to download the .jar files referenced in the `dependencies.json` file, and store them into the local `dependencies` folder.
- Phase 3: flatpak-builder builds the application in offline mode, using the material from the local `dependencies` folder.
- Phase 4: [deployment]...

The point is: the plugin is needed for phase 1, not for any of the following phases. It just happens to be listed in the dependencies, and of course flatpak-builder will try to download it and complain if it fails.

Perhaps I could remove the reference to the plugin  by post-processing the `dependenceis.json` file before handing it to flatpak-builder? [I will need to post-process it anyway, because of a trick for Linux to support `arm64` architecture beside `x86_64`]

FYI, the `schemas` sub-project is meant to provide an off-line documentation about Audiveris `.omr` files. A kind of JavaDoc if you wish. It is not needed by the end user and perhaps should be ignored by flatpak. I need to clean this up.

**Comment by hbitteur** [comment]
> Note: It takes several minutes to generate the dependencies file. You can speed this up by moving the `mavenCentral` repository above the other repositories in `gradle.build`, because the plugin tries to resolve all artifacts against the repositories in the order that they appear in the build script, and most dependenies are on Maven Central.

Indeed, it now takes 31 sec instead of 2 min 40 sec
I'm impressed. Thanks!

**Comment by jwharm** [comment]
You're correct, the plugin doesn't need to be included after it has run. You can safely remove it, as long as Gradle doesn't look for it during the offline build.

> Perhaps I could remove the reference to the plugin by post-processing the dependenceis.json file before handing it to flatpak-builder? [I will need to post-process it anyway, because of a trick for Linux to support arm64 architecture beside x86_64]

Perhaps you can add an additional configuration that "depends" on all architecture variants? It would never be used during regular builds, but the plugin should process it, and include all artifacts.

**Comment by hbitteur** [comment]
I could not find a way in Gradle to conditionally reference a plugin. We can conditionally 'apply' it, but it must be statically referenced. So, I left the plugin dependency as it is.

And regarding the trick on Linux architecture variants, I added a conditional dependency on the other architecture. No need for post-processing. Thanks for the hint!
